FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies for Python including git
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libfreetype6-dev \
        libpng-dev \
        libtiff5-dev \
        libjpeg-dev \
        openjdk-11-jdk-headless \
        curl \
        wget \
        git \
        build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Clone a GitHub repository 
RUN git clone https://github.com/Parisarahbar97/single_cell_analysis.git /app

# Continue with the rest of your installation and setup steps
RUN pip3 install --upgrade pip && pip3 install --no-cache-dir \
    scvi-tools \
    scanpy \
    anndata \
    numpy \
    pandas \
    matplotlib \
    seaborn \
    jupyter

# Install Nextflow
RUN curl -s https://get.nextflow.io | bash && \
    mv nextflow /usr/local/bin/nextflow

# Install nf-core tools 
RUN pip3 install nf-core

# Expose port 8888 for Jupyter Notebook 
EXPOSE 8888

# Default command
CMD ["bash"]
